#Farm Automations

#Electric Fence Watchgaurd, Turns back on fence after set time.
- id: 'farm 1'
  alias: Electric Fence Watch guard
  description: ''
  trigger:
  - platform: state
    entity_id: switch.sonoff_10004c01ba_4
    from: 'on'
    to: 'off'
    for:
      minutes: '{{ states(''input_number.fence_timer'')|int }}'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.sonoff_10004c01ba_4

#Switches off shed lights after set time.
- id: 'farm 2'
  alias: Auto shed Lights Off
  description: ''
  trigger:
  - platform: state
    entity_id: switch.sonoff_10004c01ba_1, switch.sonoff_10004c01ba_2, switch.sonoff_10004c01ba_3
    from: 'off'
    to: 'on'
    for:
      minutes: '{{ states(''input_number.shed_light_timer'')|int }}'
  action:
  - service: switch.turn_off
    data_template:
      entity_id: '{{ trigger.entity_id }}'